"""Initial migration.

Revision ID: 33dabebe2c28
Revises: 87f65c42538f
Create Date: 2021-11-15 17:31:06.266982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33dabebe2c28'
down_revision = '87f65c42538f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_db', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_db', 'website')
    # ### end Alembic commands ###
